version: "3"
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password

    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql-data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
